### ISSUE TITLE
Cropped vs Stitching

### ISSUE THREAD

**Issue by oisilener1982** [jixiaozhong/Sonic#11]
The demo only generates cropped version. Will there be a stitching so that we can have the animated full original uploaded image

**Comment by jixiaozhong** [comment]
We have released the inference code, and adding new features like stitching may rely on community developers to contribute.

**Comment by oisilener1982** [comment]
Thank you so much for releasing the code

**Comment by nitinmukesh** [comment]
@oisilener1982 

Did you tried. How much VRAM?

**Comment by oisilener1982** [comment]
not yet. im actually waiting for your tutorial :)

**Comment by oisilener1982** [comment]
@nitinmukesh im having a problem
(venv) D:\AI\Sonic>python3 demo.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

(venv) D:\AI\Sonic>python demo.py
Traceback (most recent call last):
  File "D:\AI\Sonic\demo.py", line 3, in <module>
    from sonic import Sonic
  File "D:\AI\Sonic\sonic.py", line 8, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

(venv) D:\AI\Sonic>
